.PHONY: clean All

All:
	@echo "----------Building project:[ part3 - Debug ]----------"
	@cd "part3" && "$(MAKE)" -f  "part3.mk"
clean:
	@echo "----------Cleaning project:[ part3 - Debug ]----------"
	@cd "part3" && "$(MAKE)" -f  "part3.mk" clean
