.PHONY: clean All

All:
	@echo "----------Building project:[ part7 - Debug ]----------"
	@cd "part7" && "$(MAKE)" -f  "part7.mk"
clean:
	@echo "----------Cleaning project:[ part7 - Debug ]----------"
	@cd "part7" && "$(MAKE)" -f  "part7.mk" clean
