.PHONY: clean All

All:
	@echo "----------Building project:[ part9 - Debug ]----------"
	@cd "part9" && "$(MAKE)" -f  "part9.mk"
clean:
	@echo "----------Cleaning project:[ part9 - Debug ]----------"
	@cd "part9" && "$(MAKE)" -f  "part9.mk" clean
