.PHONY: clean All

All:
	@echo "----------Building project:[ part8 - Debug ]----------"
	@cd "part8" && "$(MAKE)" -f  "part8.mk"
clean:
	@echo "----------Cleaning project:[ part8 - Debug ]----------"
	@cd "part8" && "$(MAKE)" -f  "part8.mk" clean
