.PHONY: clean All

All:
	@echo "----------Building project:[ part2 - Debug ]----------"
	@cd "part2" && "$(MAKE)" -f  "part2.mk"
clean:
	@echo "----------Cleaning project:[ part2 - Debug ]----------"
	@cd "part2" && "$(MAKE)" -f  "part2.mk" clean
