.PHONY: clean All

All:
	@echo "----------Building project:[ part1 - Debug ]----------"
	@cd "part1" && "$(MAKE)" -f  "part1.mk"
clean:
	@echo "----------Cleaning project:[ part1 - Debug ]----------"
	@cd "part1" && "$(MAKE)" -f  "part1.mk" clean
