.PHONY: clean All

All:
	@echo "----------Building project:[ Challeng - Debug ]----------"
	@cd "Challeng" && "$(MAKE)" -f  "Challeng.mk"
clean:
	@echo "----------Cleaning project:[ Challeng - Debug ]----------"
	@cd "Challeng" && "$(MAKE)" -f  "Challeng.mk" clean
