.PHONY: clean All

All:
	@echo "----------Building project:[ part4 - Debug ]----------"
	@cd "part4" && "$(MAKE)" -f  "part4.mk"
clean:
	@echo "----------Cleaning project:[ part4 - Debug ]----------"
	@cd "part4" && "$(MAKE)" -f  "part4.mk" clean
