.PHONY: clean All

All:
	@echo "----------Building project:[ challeng1 - Debug ]----------"
	@cd "challeng1" && "$(MAKE)" -f  "challeng1.mk"
clean:
	@echo "----------Cleaning project:[ challeng1 - Debug ]----------"
	@cd "challeng1" && "$(MAKE)" -f  "challeng1.mk" clean
