.PHONY: clean All

All:
	@echo "----------Building project:[ challeng2 - Debug ]----------"
	@cd "challeng2" && "$(MAKE)" -f  "challeng2.mk"
clean:
	@echo "----------Cleaning project:[ challeng2 - Debug ]----------"
	@cd "challeng2" && "$(MAKE)" -f  "challeng2.mk" clean
