.PHONY: clean All

All:
	@echo "----------Building project:[ challeng - Debug ]----------"
	@cd "challeng" && "$(MAKE)" -f  "challeng.mk"
clean:
	@echo "----------Cleaning project:[ challeng - Debug ]----------"
	@cd "challeng" && "$(MAKE)" -f  "challeng.mk" clean
